set nocompatible

" Dispaly
syntax enable
set hlsearch
set nu
set ruler
set cursorline
set wildmenu
set showcmd
set ignorecase
set incsearch
set smartcase
set wildmode=longest,list,full
set cmdheight=2
set laststatus=2
set matchtime=2
if exists('$TMUX')  " Support resizing in tmux
  set ttymouse=xterm2
endif
set go=
set scrolloff=3
set encoding=utf-8
set fileencodings=ucs-bom,utf-8,chinese,latin-1
" show trailing whitespace
set list
"set listchars=tab:>-,trail:▫
set listchars=tab:\|\ ,trail:-
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim
if has("gui_running")
    set guioptions-=T
    set guioptions+=e
    set t_Co=256
    set guitablabel=%M\ %t
    set langmenu=en_US.utf-8
    language messages en_US.UTF-8
endif

" Control
set confirm
set autoindent
set smartindent
set expandtab
set mouse=a
set backspace=2
set shiftwidth=4
set tabstop=4
"set whichwrap+=<,>,h,l
map j gj
map k gk
autocmd BufReadPost *
     \ if line("'\"") > 0 && line("'\"") <= line("$") |
     \   exe "normal! g`\"" |
     \ endif

" key map
let mapleader = ","
map <silent> <leader><cr> :nohl<cr>
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l
map <leader>tn :tabnew<cr>
map <leader>tc :tabclose<cr>
nmap <leader>f :NERDTreeToggle<CR>

set autoread
set clipboard=unnamed
filetype off
filetype plugin on
filetype indent on
set wildignore=*.o,*~,*.pyc,tmp/**
autocmd! BufWinEnter *    lcd %:p:h

autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType c setlocal omnifunc=ccomplete#Complete

" extension
"call pathogen#runtime_append_all_bundles()
if filereadable(expand("~/.vimrc.local"))
    source ~/.vimrc.local
endif
if filereadable(expand("~/.vimrc.bundles"))
    source ~/.vimrc.bundles
endif
